import type { Metadata } from "next";

import { Header } from "@/components/Header";
import { Navbar } from "@/components/Navbar";

import "./globals.css";

export const metadata: Metadata = {
	title: "Project Habla Mucho",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<Header />
				{children}
				<Navbar />
			</body>
		</html>
	);
}
