import type { Metadata } from "next";

import { Toaster } from "react-hot-toast";
import { Header } from "@/components/Header";

import { AppProvider } from "@/context/AppContext";
import { NavbarProvider } from "@/context/NavbarContext";
import { UsersProvider } from "@/context/UsersContext";

import "./globals.css";

export const metadata: Metadata = {
	title: "Project Habla Mucho",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en">
			<body>
				<AppProvider>
					<NavbarProvider>
						<UsersProvider>
							<Toaster position="bottom-center" reverseOrder={false} />
							<Header />
							{children}
						</UsersProvider>
					</NavbarProvider>
				</AppProvider>
			</body>
		</html>
	);
}
